@startuml Maladireta-Component
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(api, "API Backend", "Class Library.NET 8", "API Rest para a aplicacao", "BackEnd da aplicação"){
    Component(destinatariocontroller, "Controlador REST do Destinatario", "Controlador MVC", "Manipula Requisições HTTP")
    Component(destinatarioservice, "Serviço do Destinatario", "Classe de Serviço do Destinatario", "Contém a lógica de negócio do destinatario")
    Component(destinatariorepository, "Repositório do Destinatario", "Interface Repository", "Gerencia operações no banco de dados")
    Component(enderecocontroller, "Controlador REST do Endereço", "Controlador MVC", "Manipula Requisições HTTP")
    Component(enderecoservice, "Serviço do Endereço", "Classe de Serviço do Endereço", "Contém a lógica de negócio do endereço")
    Component(enderecorepository, "Repositório do Endereço", "Interface Repository", "Gerencia operações no banco de dados")
}

Rel(api, destinatariocontroller, "Chama", "Verbos HTTP")
Rel(destinatariocontroller, destinatarioservice, "Chama", "Dashed")
Rel(destinatarioservice, destinatariorepository, "Chama", "Método")
Rel(api, enderecocontroller, "Chama", "Verbos HTTP")
Rel(enderecocontroller, enderecoservice, "Chama", "Task")
Rel(enderecoservice, enderecorepository, "Chama", "Método")

@enduml