@startuml Destinatario-Code

class Destinatario {
  + Id: int
  + Nome: string
  + Email: string
  + Telefone: string?
  + Endereco: Endereco

  + Destinatario(Id: int, Nome: string, Email: string, Endereco: Endereco)
  + ValidarEmail(): bool
  + ValidarTelefone(): bool
  + ValidarEndereco(): bool
  + Validar(): bool
}

@enduml