@startuml Endereco-Code
class Endereco {
  + Logradouro: string
  + Numero: string
  + Cidade: string
  + Estado: string
  + CEP: string

  + Endereco(logradouro: string, numero: string, cidade: string, estado: string, cep: string)
  + ValidarEndereco(): bool
  + ValidarCEP(): bool
  + Exibir(): void
}
@enduml